import os
from os.path import join

Import('env', 'variant', 'idir')

dirs=[] #'cavium', 'arm']
src_local = ['mips.go', 'malta.go', 'sead3.go']
objs = []

mips_env = env.Clone()
mips_a = mips = mips_env.Go('mips', src_local)
mips = mips_env.GoPack('mips', mips_a)
mips_env.Install(idir, mips)

idir = join(idir, variant)
for variant in dirs:

	objs += SConscript(join(variant, 'SConscript'),
			   exports =['env', 'variant', 'idir'],
			   #variant_dir=sd,
			   duplicate=0)

env.Depends(mips, objs)

Return(['mips', 'objs'])
