<$VPROC/mk/mkhdr

DOFILES=\
	 gospel_cmdline.go \
	 gospel_main.go \
	 
TARG=\
	gospel_mips \
	gospel_arm \
	#vproc_ppc \
	#vproc_tilera \

gospel_%.$O: $DOFILES gospel_%.go 

NUKEFILES=$TARG

<$VPROC/mk/mkmany
