import os
from os.path import join

Import('env', 'variant', 'idir')

src_local = ['flag.go']

#flag_env = env.Clone()
#flag_a = flag_env.Go('flag', src_local)
#flag = flag_env.GoPack('flag', flag_a)
#flag_env.Install(idir, flag)

Return('src_local')
