import os
from os.path import join

Import('env', 'variant', 'idir')

src_local = ['logng.go']

#logng_env = env.Clone()
#logng_a = logng_env.Go('logng', src_local)
#logng = logng_env.GoPack('logng', logng_a)
#logng_env.Install(idir, logng)

Return('src_local')
