import os
from os.path import join

Import('env', 'variant', 'idir')

dirs=['mips'] #, 'arm']
src_local = ['plat.go', 'platld.go']

plat_env = env.Clone()
plat_a = plat_env.Go('plat', src_local)
plat = plat_env.GoPack('plat', plat_a)
plat_env.Install(idir, plat)

idir = join(idir, variant)
objs=[]
for variant in dirs:
	objs += SConscript(join(variant, 'SConscript'),
			   exports = {'env': plat_env, 'variant': variant, 'idir': idir},
			   #variant_dir=sd,
			   duplicate=0)

Depends(plat, objs)

Return(['plat', 'objs'])
