import os
from os.path import join

Import('env', 'variant', 'idir')

dirs=['mips'] #, 'arm']
common_src = ['plat.go', 'platld.go']

plat_pack = []

for sd in dirs:
	plat_env = env.Clone()
#	plat_arch = variant+sd
	plat_arch = variant
	plat_a = plat_env.Go(plat_arch, common_src)
	plat = plat_env.GoPack(plat_arch, plat_a)
	plat_env.Install(idir, plat)
	plat_pack += plat

objs = []

idir = join(idir, variant)
for variant in dirs:
	objs += SConscript(join(variant, 'SConscript'),
			   exports =['env', 'variant', 'idir'],
			   #variant_dir=sd,
			   duplicate=0)

Depends(objs, plat_pack)

Return(['plat_pack', 'objs'])
