import os
from os.path import join

Import('env', 'variant', 'idir')

dirs=['mips','arm']
cpu_src = ['main.go', 'cores.go', 'misc.go']

cpu_env = env.Clone()
cpu_a = cpu_env.Go('cpu', cpu_src)
cpu = cpu_env.GoPack('cpu', cpu_a)
cpu_env.Install(idir, cpu)

objs = []
idir = join(idir, 'cpu')

for variant in dirs:
	objs += SConscript(join(variant, 'SConscript'),
			   exports =['env', 'variant', 'idir'],
			   #variant_dir=sd,
			   duplicate=0)

Depends(objs, cpu)

Return (['cpu', 'objs'])
