import os
from os.path import join

Import('env', 'variant', 'idir')

dirs=['mips'] #'arm', 'mips']

cpu_src = ['main.go', 'cores.go', 'misc.go', 'regs.go']

cpu_env = env.Clone()
cpu_a = cpu_env.Go('cpu', cpu_src)
cpu_pack = cpu_env.GoPack('cpu', cpu_a)
cpu_env.Install(idir, cpu_pack)

objs = []
idir = join(idir, 'cpu')

for variant in dirs:
	objs += SConscript(join(variant, 'SConscript'),
			   exports ={'env': cpu_env, 'variant': variant, 'idir': idir},
			   #variant_dir = variant,
			   duplicate=0)

cpu_env.Depends(objs, cpu_pack)

Return (['objs', 'cpu_pack'])
