import os
from os.path import join

Import('env', 'bdir', 'idir')

env.Append(GO_LIBPATH=join(bdir, 'pkg'))

idir_backup=idir

utils = SConscript(join('util', 'SConscript'),
                  exports={'env': env, 'variant': 'util', 'idir': idir},
                  duplicate=0)

dirs=['cpu', 'plat'] #, 'dev']
libs = []

for variant in dirs:
	libs += SConscript(join(variant, 'SConscript'),
                           exports={'env': env, 'variant': variant, 'idir': idir},
			   #variant_dir='#build',
			   duplicate=0)

env.Depends('libs', 'utils')

progs = SConscript(join('cmd', 'SConscript'),
		   exports=['env', 'bdir', 'idir'],
		   #variant_dir='#build',
		   duplicate=0)

env.Depends('progs', 'libs')

Return(['utils', 'libs', 'progs'])
